name: Deploy to Azure with PowerShell

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      # Step 1: Check Out Repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Azure Login
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Set Up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Step 4: Run Deployment Script
      - name: Run PowerShell Deployment
        run: |
          .\deploy.ps1 `
            -ACRName "<YourACRName>" `
            -ImageName "my-api" `
            -ResourceGroup "<YourResourceGroup>" `
            -ContainerGroup "my-container-group"
        shell: pwsh
